### ISSUE TITLE
Webjars tutorial 404 on docs

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/designer-tutorials#2]
https://vaadin.com/docs/v10/designer/getting-started/designer-getting-started.html

Link to Webjars tutorial is 404 (https://vaadin.com/docs/v10/flow/web-components/tutorial-how-to-use-webjars.html)

![image](https://user-images.githubusercontent.com/26737661/44344254-e3e1a400-a498-11e8-815a-9012069b57ab.png)

**Comment by johannesh2** [comment]
Thanks for the report. Could you report it to vaadin/designer or vaadin/designer-interal. This repository is not really followed anymore. These are a collection of old tutorials, that might be still linked somewhere and thus not archived.

**Comment by mikkoi-vaadin** [comment]
Moved here: https://github.com/vaadin/designer/issues/1844
